version: "3"
  
services:
  backend:
    image: snakecharmer/backend:latest
    build: ./spring-petclinic-rest
    ports:
    - "9966:9966"

  frontend:
    image: snakecharmer/frontend:latest
    build: ./spring-petclinic-angular
    ports:
    - "8080:8080"