apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://127.0.0.1:8080;
      }
      location /petclinic/api {
        proxy_pass http://127.0.0.1:9966;
      }
    }