pipeline{
    agent any
    tools {
        maven 'Maven 3.6.3'
        jdk 'jdk9'
        node 'Node 15.1'
    }
    stages {
        stage('Test Backend') {
            steps {
                script {
                        sh 'bash jenkins/test-backend.sh'
                }
            }
        }
        stage('Test Frontend') {
            steps {
                script {
                        sh 'bash jenkins/test-frontend.sh'
                }
            }
        }
        stage('Build Docker') {
            steps {
                script {
                        sh 'bash jenkins/build_images.sh'
                }
            }
        }
    }
}
