apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
      - name: backend
        image: snakecharmer2021/backend:latest
        ports:
          - protocol: TCP
            containerPort: 9966
