apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: snakecharmer2021/frontend:latest
      ports:
        - protocol: TCP
          containerPort: 8080
